services:
  php:
    build: .
    volumes:
      - ./:/app
    ports:
      - 8081:80
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - 8082:80
